    <div id="header">
    	<div id="headercontainer">
        	<div id="branding" class="leftfloat">
            	<a href="index.php"><img src="lib/img/recipetincan.png" alt="logo" /></a>
            </div>
            <div id="login" class="rightfloat">
                <form>
                	<h2>Login</h2>
                	<input type="text" id="username"  />
                	<input type="password" id="password"  />
                </form>
            </div>
        </div>
        <div id="nav">
        	<div id="navcontainer">
            	<ol>
                	<li class="homelink"><a href="index.php">Home</a></li>
                	<li class="recipeslink"><a href="category.php	">Recipes</a></li>
                	<li class="restaurantslink"><a href="category.php">Restaurants</a></li>
                	<li class="aboutlink"><a href="about.php">About</a></li>
                </ol>
            </div>
        </div>
    </div> <!-- end header -->
